name: Package and publish addon
on:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  verify:
    uses: ./.github/workflows/test-release.yml
  release:
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Package and publish GitHub and CurseForge releases
        uses: BigWigsMods/packager@v2
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
